name: sepal-leafmap
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - sepal-ui>=2.22.2,<3
  - requests
  - gdal=3.10
  - leafmap
  - pip
  - pip:
      - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
